version: '3'

services:
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 1s
      retries: 3

  db:
    build:
      dockerfile: db/Dockerfile
      context: .

  backend:
    ports:
      - "8000:8000"
    build:
      dockerfile: backend/Dockerfile
      context: .
    volumes:
      - ./backend/:/app/backend/
    depends_on:
      - redis
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "-v", "-X GET", "-H 'Accept: application/json'", "http://localhost:8000/ht/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    ports:
      - "3000:3000"
    build:
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - ./frontend/:/app/frontend/
    depends_on:
      - redis
      - db
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
